### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [yuzumone/ExpandableTextView#37]
Hi thanks for your very useful library , but there is a problem , when I want have single line library doesn't work

**Comment by yuzumone** [comment]
The following xml worked in my environment.
If it's not working yet, please describe your code.
```
    <net.expandable.ExpandableTextView
        android:id="@+id/text"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:collapse_lines="1"
        />
```
